//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceOnlineShop.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class eCommerceConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static eCommerceConfig defaultInstance = ((eCommerceConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new eCommerceConfig())));
        
        public static eCommerceConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chrome")]
        public string Browser {
            get {
                return ((string)(this["Browser"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.opencart.com")]
        public string baseURL {
            get {
                return ((string)(this["baseURL"]));
            }
            set {
                this["baseURL"] = value;
            }
        }
    }
}
